### ISSUE TITLE
hello I would like more info about different apis

### ISSUE THREAD

**Issue by jz709u** [WataruSuzuki/ADG_iOSSDK#1]
what happens when you call 
waitShowing()?

thanks

**Comment by WataruSuzuki** [comment]
Hi, @jz709u 
This repository is only using https://github.com/AdGeneration/sdk via cocoapods for me.
So I don’t know about any SDKs detail.

**Comment by WataruSuzuki** [comment]
And this repository will be removed soon...

**Comment by jz709u** [comment]
I see thanks for your response.
